#!/bin/bash
set -e

command_exists() {
  command -v "$@" >/dev/null 2>&1
}

user_can_sudo() {
  # If sudo is available then use it, if not default to command for root enviroments
  # TODO: Add support for non root enviroments!!!
  # Adapted from https://github.com/ohmyzsh/ohmyzsh/blob/master/tools/install.sh
  command_exists sudo || return 1
  ! LANG= sudo -n -v 2>&1 | grep -q "may not run sudo"
}

update_pkgs() {
  # This takes too much, do it once
  $RUN apt update
}

install_pkgs() {
  # Wrapper to install packages depending on sudo or non-sudo enviroments
  # if user_can_sudo; then
  # $RUN apt update && apt install --no-install-recommends -y "$@"
  # else
  # # WIP
  # apt-get download $(apt-rdepends $@ | grep -v "^ ")
  # for pkg in $.deb; do dpkg -x $pkg $HOME; done
  # fi
  $RUN apt install --no-install-recommends -y "$@"
}

install_zsh() {
  install_pkgs curl zsh

  # Install ohmyzsh
  export CHSH=no
  export KEEP_ZSHRC=yes
  export RUNZSH=no
  ZSH= sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" || true
  $RUN chsh -s "$(which zsh)" "$USER" 2>/dev/null || chsh -s "$(which zsh)"

  # Install zsh-autosuggestions custom plugin
  git clone --depth 1 \
    https://github.com/zsh-users/zsh-autosuggestions \
    ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions 2>/dev/null || true

  # Copy custom configuration to the oh my sh installation
  # cp -r $HOME/.oh-my-zsh-custom/* ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/
}

minimal_installation() {
  echo "Running minimal installation, just zsh"
  install_zsh
}

# Options
RUN=$(user_can_sudo && echo "sudo" || echo "command")

main() {
  echo "Updating the yadm repo origin URL"
  yadm remote set-url origin "git@github.com:bryceikeda/dotfiles.git"

  cd "$HOME"

  # Fetch juste once the apt repositories
  update_pkgs

  minimal_installation

}

main "$@"
