#!/bin/bash
set -e

# Check if a command exists
command_exists() {
  command -v "$@" >/dev/null 2>&1
}

# Check if the user can use sudo
user_can_sudo() {
  command_exists sudo && sudo -n -v >/dev/null 2>&1
}

# Update packages
update_pkgs() {
  $RUN apt update
}

# Install packages depending on sudo or non-sudo environments
install_pkgs() {
  $RUN apt install --no-install-recommends -y "$@"
}

install_ssh(){
  install_pkgs openssh-client openssh-server sshfs
}

# Install Zsh and related components
install_zsh() {
  install_pkgs curl zsh

  # Install Oh My Zsh
  export CHSH=no
  export KEEP_ZSHRC=yes
  export RUNZSH=no
  ZSH= sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" || true
  $RUN chsh -s "$(command -v zsh)" "$USER" 2>/dev/null || chsh -s "$(command -v zsh)"

  # Install zsh-autosuggestions plugin
  git clone --depth 1 \
    https://github.com/zsh-users/zsh-autosuggestions \
    ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autosuggestions 2>/dev/null || true
}

# Perform minimal installation (just Zsh)
minimal_installation() {
  echo "Running minimal installation, currently just zsh"
  install_zsh
  install_ssh
}

full_installation(){
  echo "[WARNING] Running full installation mode, this may take some time..."

}

# Options
RUN=$(user_can_sudo && echo "sudo" || echo "command")
INSTALL_FULL=${INSTALL_FULL:-no}
DECRYPT=${DECRYPT:-no}

# Main function
main() {
  echo "Updating the yadm repo origin URL"
  yadm remote set-url origin "git@github.com:bryceikeda/dotfiles.git"

  cd "$HOME"

  # Fetch apt repositories only once
  update_pkgs

  minimal_installation
  
  if [ $INSTALL_FULL = yes ]; then
    full_installation
  fi



}

# Call the main function
main "$@"
